import type { Metadata } from "next";
import { notoSerif } from "@/app/ui/fonts";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "My Tiny Journal App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSerif.className} antialiased`}>{children}</body>
    </html>
  );
}
